### ISSUE TITLE
TypeError: Paths.cir() got an unexpected keyword argument 'num_paths' when running tutorial script

### ISSUE THREAD

**Issue by Virusx51** [NVlabs/sionna#317]
Hi, 

Hello,
I tried running the script mentioned in the tutorial, but I'm getting an error. [Tutorial](https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Introduction.html#Site-specifc-Link-Level-Simulations)

TypeError                                 Traceback (most recent call last)
Cell In[40], line 48
     41 paths.apply_doppler(sampling_frequency=subcarrier_spacing,
     42                     num_time_steps=14,
     43                     tx_velocities=[0.,0.,0],
     44                     rx_velocities=[3.,3.,0])
     46 # We fix here the maximum number of paths to 75 which ensures
     47 # that we can simply concatenate different channel impulse reponses
---> 48 a_, tau_ = paths.cir(num_paths = 75)
     49 del paths # Free memory
     51 if a is None:

TypeError: Paths.cir() got an unexpected keyword argument 'num_paths'

![image](https://github.com/NVlabs/sionna/assets/71511652/bf9e02ac-0013-4ee2-81e0-f643071318f4)

**Comment by faycalaa** [comment]
Hi,

The `num_paths` parameter of `Paths.cir()` was introduced in version 0.16 of Sionna. Are you using the latest version of Sionna?

**Comment by Virusx51** [comment]
Thank you for your response. 
Now it's clear. I had a problem installing the latest version on Windows 10, so I installed Sionna 0.15. As I understood, Ubuntu 22.04 is recommended for proper operation. What operating system are you using?

**Comment by faycalaa** [comment]
The latest version of Sionna should work with Ubuntu 22.04.

**Comment by Virusx51** [comment]
Thank you very much for the quick response. I will try to set it up through WSL. In the professional version of PyCharm, there is an option to forward the virtual environment
